version: "3.8"

services:
  db:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicles
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/user/postgres/:/var/lib/postgresql/data/
