name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Health check to wait until Postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Install SQLite
        run: go install github.com/mattn/go-sqlite3

      - name: Run tests
        run: go test ./...
        env:
          DATABASE_URL: "host=localhost port=5432 user=admin password=postgres dbname=testdb sslmode=disable"
